#!/usr/bin/env bash
# Generate verilog/dv/cocotb/design_info.local.yaml for running cocotb outside the container.
#
# This keeps design_info.yaml pointing at container defaults, while letting each developer
# have a per-machine override (git-ignored).
#
# Usage (from anywhere inside the repo):
#   verilog/dv/cocotb/mk_design_info_local.sh
#   caravel_cocotb -t hello_world_uart -tag hello_world \
#     -design_info verilog/dv/cocotb/design_info.local.yaml
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)"
if [[ -z "${repo_root}" ]]; then
  echo "ERROR: must be run from within a git checkout (could not find repo root)." >&2
  exit 1
fi

out="${repo_root}/verilog/dv/cocotb/design_info.local.yaml"

cat >"${out}" <<EOF
# Auto-generated by verilog/dv/cocotb/mk_design_info_local.sh
#
# This file is git-ignored. Re-run the script if you move/rename your checkout.

CARAVEL_ROOT: ${repo_root}/caravel
MCW_ROOT: ${repo_root}/mgmt_core_wrapper
PDK: sky130A
PDK_ROOT: ${repo_root}/dependencies/pdks
USER_PROJECT_ROOT: ${repo_root}
caravan: false
clk: 25
emailto:
- null
EOF

echo "Wrote: ${out}"
