# AUTOGENERATED: do not hand-edit
# Source: ip/home-inventory-chip/rtl/ip_home_inventory.f
# Generated: <timestamp elided>
# Canonical RTL filelist for the Home Inventory IP (chip-inventory)
# Paths are relative to the chip-inventory repo root.
#
# Harness repo should either:
#   (a) maintain its own filelist that mirrors this one, OR
#   (b) generate a harness-relative filelist by prefixing each line with:
#       ip/home-inventory-chip/

ip/home-inventory-chip/rtl/include/home_inventory_regmap_pkg.sv
ip/home-inventory-chip/rtl/include/regmap_params.vh

ip/home-inventory-chip/rtl/home_inventory_wb.v
ip/home-inventory-chip/rtl/home_inventory_event_detector.v
ip/home-inventory-chip/rtl/adc/adc_drdy_sync.v
ip/home-inventory-chip/rtl/adc/adc_stream_fifo.v
ip/home-inventory-chip/rtl/adc/adc_spi_frame_capture.v
ip/home-inventory-chip/rtl/adc/adc_frame_to_fifo.v
ip/home-inventory-chip/rtl/adc/adc_streaming_ingest.v
ip/home-inventory-chip/rtl/home_inventory_top.v
