#!/usr/bin/env bash
set -euo pipefail

# Sync the harness RTL filelist from the source-of-truth IP submodule.
#
# Canonical list lives at:
#   ip/home-inventory-chip/rtl/ip_home_inventory.f
#
# This script generates:
#   verilog/rtl/ip_home_inventory.f
#
# Why: keep ordering + membership identical between repos.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANON_F="${ROOT_DIR}/ip/home-inventory-chip/rtl/ip_home_inventory.f"
OUT_F="${ROOT_DIR}/verilog/rtl/ip_home_inventory.f"

if [[ ! -f "${CANON_F}" ]]; then
  echo "ERROR: canonical filelist not found: ${CANON_F}" >&2
  echo "Did you init submodules?" >&2
  echo "  git submodule update --init --recursive" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_F}")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# AUTOGENERATED: do not hand-edit"
  echo "# Source: ip/home-inventory-chip/rtl/ip_home_inventory.f"
  echo "# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  # Prefix *only* real path lines so the harness compilers can find the IP RTL.
  # Keep comments and blank lines intact.
  awk '
    /^\s*#/ {print; next}
    /^\s*$/ {print; next}
    {print "ip/home-inventory-chip/" $0}
  ' "${CANON_F}"
} >"${tmp}"

# Only overwrite if content actually changed (keeps git diffs clean).
if [[ -f "${OUT_F}" ]] && cmp -s "${tmp}" "${OUT_F}"; then
  echo "OK: already up to date: ${OUT_F}"
  exit 0
fi

mv "${tmp}" "${OUT_F}"
trap - EXIT

echo "OK: updated ${OUT_F}"